# Generated by Django 3.2.7 on 2022-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cocina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosCocina',
            fields=[
                ('idpedidos_cocina', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'idpedidos_cocina',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pedidos_cocina',
        ),
    ]
