# Generated by Django 3.2.7 on 2022-11-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cocina', '0002_auto_20221117_0324'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidoscocina',
            table='pedidos_cocina',
        ),
    ]
