# Generated by Django 3.2.7 on 2022-11-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cocina', '0003_alter_pedidoscocina_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoscocina',
            options={'managed': True},
        ),
    ]
