# Generated by Django 3.2.7 on 2022-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_PRODUCTO', models.CharField(max_length=255)),
                ('FECHA_DE_VENCIMIENTO', models.CharField(max_length=20)),
                ('STOCK_PRODUCTO', models.IntegerField()),
                ('DESC_PRODUCTO', models.CharField(max_length=255)),
                ('PRECIO_PRODUCTO', models.IntegerField()),
                ('STOCK_CRITICO', models.IntegerField()),
            ],
        ),
    ]
