# Generated by Django 3.2.7 on 2022-11-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
