# Generated by Django 3.2.7 on 2022-11-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
